# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-25 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annies_portfolio_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='/'),
        ),
    ]
