# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annies_portfolio_site', '0004_auto_20161226_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='/media/'),
        ),
    ]
