# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 19:49
from __future__ import unicode_literals

import annies_portfolio_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annies_portfolio_site', '0006_auto_20161226_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=annies_portfolio_site.models.rename_upload),
        ),
    ]
