# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annies_portfolio_site', '0007_auto_20161226_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturepost',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
