# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annies_portfolio_site', '0010_auto_20161226_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturepost',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
