# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annies_portfolio_site', '0011_auto_20161230_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annies_portfolio_site.Picture'),
        ),
    ]
