# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annies_portfolio_site', '0012_auto_20161230_1933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Medium',
        ),
        migrations.RenameField(
            model_name='medium',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='picturepost',
            old_name='category',
            new_name='medium',
        ),
        migrations.AddField(
            model_name='picturepost',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picturepost',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
