# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annies_portfolio_site', '0013_auto_20170104_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturepost',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='picturepost',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='picturepost',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
