# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-05 13:37
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('annies_portfolio_site', '0016_blogpost_thumbnail_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
